
logger:
    console:
        level: INFO

# Cognite project to stream your datapoints from
cognite:
    host: ${COGNITE_BASE_URL}
    project: ${COGNITE_PROJECT}

    idp-authentication:
        token-url: ${COGNITE_TOKEN_URL}
        client-id: ${COGNITE_CLIENT_ID}
        secret: ${COGNITE_CLIENT_SECRET}
        scopes:
            - ${COGNITE_BASE_URL}/.default
    extraction-pipeline:
        external-id: fabric-replicator

#Extractor config
extractor:
    state-store:
        local:
            path: state.json
    subscription-batch-size: 10000
    ingest-batch-size: 100000
    poll-time: 5

# lakehouse details
lakehouse:
  lakehouse_table_name: ${LAKEHOUSE_TABLE_NAME}

# subscriptions to stream
#subscriptions:
#  - externalId: ts-subscription
#    partitions:
#        - 0

data_modeling:
    - space: cc_plant
